project:
  type: book

book:
  title: "ankivalenz-quarto-book"
  author: "Harry Vangberg"
  date: "now"
  chapters:
    - index.qmd
    - front-back.qmd
    - cloze.qmd

format:
  html:
    theme: cosmo
  ankivalenz-html: default
  pdf:
    documentclass: scrreprt

editor: visual

